
package com.webxml.traditionalsimplified;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>中文简体字<->繁体字转换 WEB 服务</strong><br />此中文简体字<->繁体字转换Web Services请不要用于任何商业目的，若有需要请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，欢迎技术交流。 QQ：8409035<br /><strong>使用本站 WEB 服务请注明或链接本站：http://www.webxml.com.cn/ 感谢大家的支持</strong>！<br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TraditionalSimplifiedWebService", targetNamespace = "http://webxml.com.cn/", wsdlLocation = "http://webservice.webxml.com.cn/WebServices/TraditionalSimplifiedWebService.asmx?wsdl")
public class TraditionalSimplifiedWebService
    extends Service
{

    private final static URL TRADITIONALSIMPLIFIEDWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.webxml.traditionalsimplified.TraditionalSimplifiedWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.webxml.traditionalsimplified.TraditionalSimplifiedWebService.class.getResource(".");
            url = new URL(baseUrl, "http://webservice.webxml.com.cn/WebServices/TraditionalSimplifiedWebService.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://webservice.webxml.com.cn/WebServices/TraditionalSimplifiedWebService.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TRADITIONALSIMPLIFIEDWEBSERVICE_WSDL_LOCATION = url;
    }

    public TraditionalSimplifiedWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TraditionalSimplifiedWebService() {
        super(TRADITIONALSIMPLIFIEDWEBSERVICE_WSDL_LOCATION, new QName("http://webxml.com.cn/", "TraditionalSimplifiedWebService"));
    }

    /**
     * 
     * @return
     *     returns TraditionalSimplifiedWebServiceSoap
     */
    @WebEndpoint(name = "TraditionalSimplifiedWebServiceSoap")
    public TraditionalSimplifiedWebServiceSoap getTraditionalSimplifiedWebServiceSoap() {
        return super.getPort(new QName("http://webxml.com.cn/", "TraditionalSimplifiedWebServiceSoap"), TraditionalSimplifiedWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TraditionalSimplifiedWebServiceSoap
     */
    @WebEndpoint(name = "TraditionalSimplifiedWebServiceSoap")
    public TraditionalSimplifiedWebServiceSoap getTraditionalSimplifiedWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://webxml.com.cn/", "TraditionalSimplifiedWebServiceSoap"), TraditionalSimplifiedWebServiceSoap.class, features);
    }

}
