
package com.webxml.translator;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>中文<->英文双向翻译 WEB 服务</strong>，本词典库中大部分单词是由程序根据词频和英<->中单词间相互关联程度自动生成，难免存在有解释错误和牵强的地方请大家谅解。</br>此中文<->英文双向翻译Web Services请不要用于任何商业目的，若有需要请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，欢迎技术交流。 QQ：8409035<br /><strong>使用本站 WEB 服务请注明或链接本站：http://www.webxml.com.cn/ 感谢大家的支持</strong>！<br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TranslatorWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "http://webservice.webxml.com.cn/WebServices/TranslatorWebService.asmx?wsdl")
public class TranslatorWebService
    extends Service
{

    private final static URL TRANSLATORWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.webxml.translator.TranslatorWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.webxml.translator.TranslatorWebService.class.getResource(".");
            url = new URL(baseUrl, "http://webservice.webxml.com.cn/WebServices/TranslatorWebService.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://webservice.webxml.com.cn/WebServices/TranslatorWebService.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TRANSLATORWEBSERVICE_WSDL_LOCATION = url;
    }

    public TranslatorWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TranslatorWebService() {
        super(TRANSLATORWEBSERVICE_WSDL_LOCATION, new QName("http://WebXml.com.cn/", "TranslatorWebService"));
    }

    /**
     * 
     * @return
     *     returns TranslatorWebServiceSoap
     */
    @WebEndpoint(name = "TranslatorWebServiceSoap")
    public TranslatorWebServiceSoap getTranslatorWebServiceSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "TranslatorWebServiceSoap"), TranslatorWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TranslatorWebServiceSoap
     */
    @WebEndpoint(name = "TranslatorWebServiceSoap")
    public TranslatorWebServiceSoap getTranslatorWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "TranslatorWebServiceSoap"), TranslatorWebServiceSoap.class, features);
    }

}
